using System;
using Foundation.Lighthouse.Diagnostics;
using Foundation.Lighthouse.Model.Autogenerated.Concrete.Foundation.Lighthouse.Partial;
using Sitecore.Data.Managers;
using Sitecore.Shell.Framework.Commands;
using Sitecore.Web.UI.Sheer;

namespace Foundation.Lighthouse.Commands
{
    public class Base : Command
    {
        public override void Execute(CommandContext context)
        {
            throw new Exception("This method should not be called");
        }

        protected bool Verify(CommandContext context)
        {
            var item = context.Items[0];
            var itemTemplate = TemplateManager.GetTemplate(item);
            if (!itemTemplate.InheritsFrom(_Lighthouse.ItemTemplateId))
            {
                LighthouseLog.Error($"Error during attempt to execute {this.Name}. Item {item.Paths.FullPath} is not inherited from _Lighthouse item");
                var lighthouseTemplate = Sitecore.Data.Database.GetDatabase("master").GetItem(_Lighthouse.ItemTemplateId);
                SheerResponse.ShowError("Could not run this command",
                    $"You want to run Lighthouse command on item that is not inherited from Lighthouse template. Please inherit item from _Lighthouse({lighthouseTemplate.Paths.FullPath}) template and try again.");
                return false;
            }
            
            return true;
        }
    }
}