using System;
using System.Collections.Generic;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Foundation.Lighthouse.Model.Autogenerated
{
    public partial class LighthouseJson
    {
        public string UserAgent { get; set; }
        public Environment Environment { get; set; }
        public string LighthouseVersion { get; set; }
        public DateTimeOffset FetchTime { get; set; }
        public Uri RequestedUrl { get; set; }
        public Uri FinalUrl { get; set; }
        public object[] RunWarnings { get; set; }
        public Audits Audits { get; set; }
        public ConfigSettings ConfigSettings { get; set; }
        public Categories Categories { get; set; }
        public CategoryGroups CategoryGroups { get; set; }
        public Timing Timing { get; set; }
        public I18N I18N { get; set; }
        public object[] StackPacks { get; set; }
    }

    public partial class Audits
    {
        public BeijingPigeon IsOnHttps { get; set; }
        public PuneHedgehog RedirectsHttp { get; set; }
        public BootupTime ServiceWorker { get; set; }
        public BeijingPigeon WorksOffline { get; set; }
        public BeijingPigeon Viewport { get; set; }
        public BeijingPigeon WithoutJavascript { get; set; }
        public BeijingPigeon FirstContentfulPaint { get; set; }
        public BeijingPigeon FirstMeaningfulPaint { get; set; }
        public PuneHedgehog LoadFastEnoughForPwa { get; set; }
        public BootupTime SpeedIndex { get; set; }
        public PuneHedgehog ScreenshotThumbnails { get; set; }
        public PuneHedgehog FinalScreenshot { get; set; }
        public BootupTime EstimatedInputLatency { get; set; }
        public EfficientAnimatedContent TotalBlockingTime { get; set; }
        public PuneHedgehog MaxPotentialFid { get; set; }
        public PuneHedgehog ErrorsInConsole { get; set; }
        public BeijingPigeon TimeToFirstByte { get; set; }
        public BeijingPigeon FirstCpuIdle { get; set; }
        public BootupTime Interactive { get; set; }
        public BeijingPigeon UserTimings { get; set; }
        public BeijingPigeon CriticalRequestChains { get; set; }
        public PuneHedgehog Redirects { get; set; }
        public PuneHedgehog InstallableManifest { get; set; }
        public PuneHedgehog AppleTouchIcon { get; set; }
        public PuneHedgehog SplashScreen { get; set; }
        public PuneHedgehog ThemedOmnibox { get; set; }
        public PuneHedgehog ContentWidth { get; set; }
        public PuneHedgehog ImageAspectRatio { get; set; }
        public PuneHedgehog Deprecations { get; set; }
        public PuneHedgehog MainthreadWorkBreakdown { get; set; }
        public BootupTime BootupTime { get; set; }
        public BeijingPigeon UsesRelPreload { get; set; }
        public BeijingPigeon UsesRelPreconnect { get; set; }
        public PuneHedgehog FontDisplay { get; set; }
        public PuneHedgehog Diagnostics { get; set; }
        public BootupTime NetworkRequests { get; set; }
        public BootupTime NetworkRtt { get; set; }
        public PuneHedgehog NetworkServerLatency { get; set; }
        public PuneHedgehog MainThreadTasks { get; set; }
        public BeijingPigeon Metrics { get; set; }
        public PuneHedgehog OfflineStartUrl { get; set; }
        public PuneHedgehog PerformanceBudget { get; set; }
        public PuneHedgehog ResourceSummary { get; set; }
        public BeijingPigeon ThirdPartySummary { get; set; }
        public PuneHedgehog PwaCrossBrowser { get; set; }
        public PuneHedgehog PwaPageTransitions { get; set; }
        public PuneHedgehog PwaEachPageHasUrl { get; set; }
        public PuneHedgehog Accesskeys { get; set; }
        public PuneHedgehog AriaAllowedAttr { get; set; }
        public PuneHedgehog AriaRequiredAttr { get; set; }
        public PuneHedgehog AriaRequiredChildren { get; set; }
        public PuneHedgehog AriaRequiredParent { get; set; }
        public PuneHedgehog AriaRoles { get; set; }
        public PuneHedgehog AriaValidAttrValue { get; set; }
        public PuneHedgehog AriaValidAttr { get; set; }
        public PuneHedgehog AudioCaption { get; set; }
        public PuneHedgehog ButtonName { get; set; }
        public PuneHedgehog Bypass { get; set; }
        public PuneHedgehog ColorContrast { get; set; }
        public PuneHedgehog DefinitionList { get; set; }
        public PuneHedgehog Dlitem { get; set; }
        public PuneHedgehog DocumentTitle { get; set; }
        public PuneHedgehog DuplicateId { get; set; }
        public PuneHedgehog FrameTitle { get; set; }
        public PuneHedgehog HtmlHasLang { get; set; }
        public PuneHedgehog HtmlLangValid { get; set; }
        public PuneHedgehog ImageAlt { get; set; }
        public PuneHedgehog InputImageAlt { get; set; }
        public PuneHedgehog Label { get; set; }
        public PuneHedgehog LayoutTable { get; set; }
        public PuneHedgehog LinkName { get; set; }
        public PuneHedgehog List { get; set; }
        public PuneHedgehog Listitem { get; set; }
        public PuneHedgehog MetaRefresh { get; set; }
        public PuneHedgehog MetaViewport { get; set; }
        public PuneHedgehog ObjectAlt { get; set; }
        public PuneHedgehog Tabindex { get; set; }
        public BeijingPigeon TdHeadersAttr { get; set; }
        public BeijingPigeon ThHasDataCells { get; set; }
        public BeijingPigeon ValidLang { get; set; }
        public BeijingPigeon VideoCaption { get; set; }
        public BeijingPigeon VideoDescription { get; set; }
        public PuneHedgehog CustomControlsLabels { get; set; }
        public PuneHedgehog CustomControlsRoles { get; set; }
        public PuneHedgehog FocusTraps { get; set; }
        public PuneHedgehog FocusableControls { get; set; }
        public PuneHedgehog HeadingLevels { get; set; }
        public PuneHedgehog InteractiveElementAffordance { get; set; }
        public PuneHedgehog LogicalTabOrder { get; set; }
        public PuneHedgehog ManagedFocus { get; set; }
        public PuneHedgehog OffscreenContentHidden { get; set; }
        public BeijingPigeon UseLandmarks { get; set; }
        public BeijingPigeon VisualOrderFollowsDom { get; set; }
        public EfficientAnimatedContent UsesLongCacheTtl { get; set; }
        public EfficientAnimatedContent TotalByteWeight { get; set; }
        public PuneHedgehog OffscreenImages { get; set; }
        public PuneHedgehog RenderBlockingResources { get; set; }
        public EfficientAnimatedContent UnminifiedCss { get; set; }
        public BeijingPigeon UnminifiedJavascript { get; set; }
        public BeijingPigeon UnusedCssRules { get; set; }
        public BeijingPigeon UsesWebpImages { get; set; }
        public EfficientAnimatedContent UsesOptimizedImages { get; set; }
        public BeijingPigeon UsesTextCompression { get; set; }
        public BeijingPigeon UsesResponsiveImages { get; set; }
        public EfficientAnimatedContent EfficientAnimatedContent { get; set; }
        public PuneHedgehog AppcacheManifest { get; set; }
        public PuneHedgehog Doctype { get; set; }
        public PuneHedgehog DomSize { get; set; }
        public PuneHedgehog ExternalAnchorsUseRelNoopener { get; set; }
        public PuneHedgehog GeolocationOnStart { get; set; }
        public BootupTime NoDocumentWrite { get; set; }
        public BeijingPigeon NoVulnerableLibraries { get; set; }
        public PuneHedgehog JsLibraries { get; set; }
        public BeijingPigeon NotificationOnStart { get; set; }
        public PuneHedgehog PasswordInputsCanBePastedInto { get; set; }
        public EfficientAnimatedContent UsesHttp2 { get; set; }
        public EfficientAnimatedContent UsesPassiveEventListeners { get; set; }
        public PuneHedgehog MetaDescription { get; set; }
        public PuneHedgehog HttpStatusCode { get; set; }
        public PuneHedgehog FontSize { get; set; }
        public PuneHedgehog LinkText { get; set; }
        public PuneHedgehog IsCrawlable { get; set; }
        public BeijingPigeon RobotsTxt { get; set; }
        public BeijingPigeon TapTargets { get; set; }
        public PuneHedgehog Hreflang { get; set; }
        public PuneHedgehog Plugins { get; set; }
        public PuneHedgehog Canonical { get; set; }
        public PuneHedgehog StructuredData { get; set; }
    }

    public partial class PuneHedgehog
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double? Score { get; set; }
        public ScoreDisplayMode ScoreDisplayMode { get; set; }
        public object[] Warnings { get; set; }
        public PurpleDetails Details { get; set; }
        public string Explanation { get; set; }
        public string DisplayValue { get; set; }
        public double? NumericValue { get; set; }
    }

    public partial class PurpleDetails
    {
        public DebugDataType Type { get; set; }
        public PurpleHeading[] Headings { get; set; }
        public PurpleItem[] Items { get; set; }
        public DetailsDebugData DebugData { get; set; }
        public long? Timing { get; set; }
        public long? Timestamp { get; set; }
        public string Data { get; set; }
        public PurpleSummary Summary { get; set; }
        public long? OverallSavingsMs { get; set; }
        public long? OverallSavingsBytes { get; set; }
        public long? Scale { get; set; }
    }

    public partial class DetailsDebugData
    {
        public DebugDataType Type { get; set; }
        public string Impact { get; set; }
        public string[] Tags { get; set; }
    }

    public partial class PurpleHeading
    {
        public string Key { get; set; }
        public string ItemType { get; set; }
        public string Text { get; set; }
        public long? Granularity { get; set; }
        public ValueType? ValueType { get; set; }
        public string Label { get; set; }
    }

    public partial class PurpleItem
    {
        public Node Node { get; set; }
        public long? NumRequests { get; set; }
        public long? NumScripts { get; set; }
        public long? NumStylesheets { get; set; }
        public long? NumFonts { get; set; }
        public long? NumTasks { get; set; }
        public long? NumTasksOver10Ms { get; set; }
        public long? NumTasksOver25Ms { get; set; }
        public long? NumTasksOver50Ms { get; set; }
        public long? NumTasksOver100Ms { get; set; }
        public long? NumTasksOver500Ms { get; set; }
        public double? Rtt { get; set; }
        public double? Throughput { get; set; }
        public double? MaxRtt { get; set; }
        public double? MaxServerLatency { get; set; }
        public long? TotalByteWeight { get; set; }
        public double? TotalTaskTime { get; set; }
        public long? MainDocumentTransferSize { get; set; }
        public string Statistic { get; set; }
        public ElementUnion? Element { get; set; }
        public long? Value { get; set; }
        public SourceUnion? Source { get; set; }
        public string Description { get; set; }
        public Uri Url { get; set; }
        public double? WastedMs { get; set; }
        public string Selector { get; set; }
        public string Coverage { get; set; }
        public string FontSize { get; set; }
        public string[] Failures { get; set; }
        public bool? IsParseFailure { get; set; }
        public string ParseFailureReason { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string Npm { get; set; }
        public double? Duration { get; set; }
        public double? StartTime { get; set; }
        public string Group { get; set; }
        public string GroupLabel { get; set; }
        public Uri Origin { get; set; }
        public double? ServerResponseTime { get; set; }
        public double? RequestStartTime { get; set; }
        public long? TotalBytes { get; set; }
        public long? WastedBytes { get; set; }
        public long? WastedPercent { get; set; }
        public string ResourceType { get; set; }
        public string Label { get; set; }
        public long? RequestCount { get; set; }
        public long? Size { get; set; }
        public long? Timing { get; set; }
        public long? Timestamp { get; set; }
        public string Data { get; set; }
        public object ThemeColor { get; set; }
    }

    public partial class ElementClass
    {
        public string Type { get; set; }
        public string Value { get; set; }
    }

    public partial class Node
    {
        public NodeType Type { get; set; }
        public string Selector { get; set; }
        public string Path { get; set; }
        public string Snippet { get; set; }
        public string Explanation { get; set; }
        public string NodeLabel { get; set; }
    }

    public partial class PurpleSummary
    {
    }

    public partial class BootupTime
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double? Score { get; set; }
        public ScoreDisplayMode ScoreDisplayMode { get; set; }
        public double? NumericValue { get; set; }
        public string DisplayValue { get; set; }
        public BootupTimeDetails Details { get; set; }
    }

    public partial class BootupTimeDetails
    {
        public DebugDataType Type { get; set; }
        public FluffyHeading[] Headings { get; set; }
        public FluffyItem[] Items { get; set; }
        public FluffySummary Summary { get; set; }
        public DetailsDebugData DebugData { get; set; }
        public double? OverallSavingsMs { get; set; }
    }

    public partial class FluffyHeading
    {
        public string Key { get; set; }
        public string ItemType { get; set; }
        public string Text { get; set; }
        public long? Granularity { get; set; }
        public string DisplayUnit { get; set; }
        public ValueType? ValueType { get; set; }
        public string Label { get; set; }
    }

    public partial class FluffyItem
    {
        public string Url { get; set; }
        public double? Total { get; set; }
        public double? Scripting { get; set; }
        public double? ScriptParseCompile { get; set; }
        public Node Node { get; set; }
        public string Statistic { get; set; }
        public ElementUnion? Element { get; set; }
        public long? Value { get; set; }
        public SourceUnion? Source { get; set; }
        public string Description { get; set; }
        public double? WastedMs { get; set; }
        public string Selector { get; set; }
        public string Coverage { get; set; }
        public string FontSize { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string Npm { get; set; }
        public double? Duration { get; set; }
        public double? StartTime { get; set; }
        public string Group { get; set; }
        public string GroupLabel { get; set; }
        public double? EndTime { get; set; }
        public long? TransferSize { get; set; }
        public long? ResourceSize { get; set; }
        public long? StatusCode { get; set; }
        public MimeType? MimeType { get; set; }
        public string ResourceType { get; set; }
        public Uri Origin { get; set; }
        public double? Rtt { get; set; }
        public double? ServerResponseTime { get; set; }
        public string HighestSeverity { get; set; }
        public long? VulnCount { get; set; }
        public DetectedLib DetectedLib { get; set; }
        public long? TotalBytes { get; set; }
        public string Label { get; set; }
        public long? RequestCount { get; set; }
        public long? Size { get; set; }
        public long? CacheLifetimeMs { get; set; }
        public double? CacheHitProbability { get; set; }
        public double? WastedBytes { get; set; }
        public ItemDebugData DebugData { get; set; }
    }

    public partial class ItemDebugData
    {
        public DebugDataType Type { get; set; }
        public bool Public { get; set; }
        public long MaxAge { get; set; }
    }

    public partial class DetectedLib
    {
        public string Text { get; set; }
        public Uri Url { get; set; }
        public string Type { get; set; }
    }

    public partial class FluffySummary
    {
        public double? WastedMs { get; set; }
        public double? WastedBytes { get; set; }
    }

    public partial class BeijingPigeon
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double? Score { get; set; }
        public ScoreDisplayMode ScoreDisplayMode { get; set; }
        public string DisplayValue { get; set; }
        public FluffyDetails Details { get; set; }
        public double? NumericValue { get; set; }
        public object[] Warnings { get; set; }
    }

    public partial class FluffyDetails
    {
        public DebugDataType Type { get; set; }
        public Chains Chains { get; set; }
        public LongestChain LongestChain { get; set; }
        public TentacledHeading[] Headings { get; set; }
        public TentacledItem[] Items { get; set; }
        public PurpleSummary Summary { get; set; }
        public double? OverallSavingsMs { get; set; }
        public long? OverallSavingsBytes { get; set; }
    }

    public partial class Chains
    {
        public The0Cc45Bddf4C0A2D88261Bd49Ad98461B The0Cc45Bddf4C0A2D88261Bd49Ad98461B { get; set; }
        public The26668226 The26668226 { get; set; }
    }

    public partial class The0Cc45Bddf4C0A2D88261Bd49Ad98461B
    {
        public Request Request { get; set; }
        public Dictionary<string, The26668226> Children { get; set; }
    }

    public partial class The26668226
    {
        public Request Request { get; set; }
    }

    public partial class Request
    {
        public Uri Url { get; set; }
        public double StartTime { get; set; }
        public double EndTime { get; set; }
        public double ResponseReceivedTime { get; set; }
        public long TransferSize { get; set; }
    }

    public partial class TentacledHeading
    {
        public string Key { get; set; }
        public string ItemType { get; set; }
        public string Text { get; set; }
        public ValueType? ValueType { get; set; }
        public string Label { get; set; }
    }

    public partial class TentacledItem
    {
        public long? FirstContentfulPaint { get; set; }
        public long? FirstMeaningfulPaint { get; set; }
        public long? FirstCpuIdle { get; set; }
        public long? Interactive { get; set; }
        public long? SpeedIndex { get; set; }
        public long? EstimatedInputLatency { get; set; }
        public long? TotalBlockingTime { get; set; }
        public long? ObservedNavigationStart { get; set; }
        public long? ObservedNavigationStartTs { get; set; }
        public long? ObservedFirstPaint { get; set; }
        public long? ObservedFirstPaintTs { get; set; }
        public long? ObservedFirstContentfulPaint { get; set; }
        public long? ObservedFirstContentfulPaintTs { get; set; }
        public long? ObservedFirstMeaningfulPaint { get; set; }
        public long? ObservedFirstMeaningfulPaintTs { get; set; }
        public long? ObservedLargestContentfulPaint { get; set; }
        public long? ObservedLargestContentfulPaintTs { get; set; }
        public long? ObservedTraceEnd { get; set; }
        public long? ObservedTraceEndTs { get; set; }
        public long? ObservedLoad { get; set; }
        public long? ObservedLoadTs { get; set; }
        public long? ObservedDomContentLoaded { get; set; }
        public long? ObservedDomContentLoadedTs { get; set; }
        public long? ObservedFirstVisualChange { get; set; }
        public long? ObservedFirstVisualChangeTs { get; set; }
        public long? ObservedLastVisualChange { get; set; }
        public long? ObservedLastVisualChangeTs { get; set; }
        public long? ObservedSpeedIndex { get; set; }
        public long? ObservedSpeedIndexTs { get; set; }
        public bool? LcpInvalidated { get; set; }
        public string HighestSeverity { get; set; }
        public long? VulnCount { get; set; }
        public DetectedLib DetectedLib { get; set; }
        public Uri Url { get; set; }
        public long? WastedBytes { get; set; }
        public double? WastedPercent { get; set; }
        public long? TotalBytes { get; set; }
        public bool? FromProtocol { get; set; }
        public bool? IsCrossOrigin { get; set; }
    }

    public partial class LongestChain
    {
        public double Duration { get; set; }
        public long Length { get; set; }
        public long TransferSize { get; set; }
    }

    public partial class EfficientAnimatedContent
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Score { get; set; }
        public ScoreDisplayMode ScoreDisplayMode { get; set; }
        public double? NumericValue { get; set; }
        public string DisplayValue { get; set; }
        public EfficientAnimatedContentDetails Details { get; set; }
        public object[] Warnings { get; set; }
    }

    public partial class EfficientAnimatedContentDetails
    {
        public DebugDataType Type { get; set; }
        public StickyHeading[] Headings { get; set; }
        public StickyItem[] Items { get; set; }
        public long? OverallSavingsMs { get; set; }
        public long? OverallSavingsBytes { get; set; }
        public ValuesClass Summary { get; set; }
    }

    public partial class StickyHeading
    {
        public string Key { get; set; }
        public string ItemType { get; set; }
        public string Text { get; set; }
        public long? Granularity { get; set; }
        public string DisplayUnit { get; set; }
    }

    public partial class StickyItem
    {
        public Uri Url { get; set; }
        public long? TotalBytes { get; set; }
        public long? CacheLifetimeMs { get; set; }
        public double? CacheHitProbability { get; set; }
        public double? WastedBytes { get; set; }
        public ItemDebugData DebugData { get; set; }
        public string Label { get; set; }
    }

    public partial class ValuesClass
    {
        public double WastedBytes { get; set; }
    }

    public partial class Categories
    {
        public Performance Performance { get; set; }
        public Accessibility Accessibility { get; set; }
        public BestPractices BestPractices { get; set; }
        public Accessibility Seo { get; set; }
        public Accessibility Pwa { get; set; }
    }

    public partial class Accessibility
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string ManualDescription { get; set; }
        public AccessibilityAuditRef[] AuditRefs { get; set; }
        public string Id { get; set; }
        public double Score { get; set; }
    }

    public partial class AccessibilityAuditRef
    {
        public string Id { get; set; }
        public long Weight { get; set; }
        public string Group { get; set; }
    }

    public partial class BestPractices
    {
        public string Title { get; set; }
        public BestPracticesAuditRef[] AuditRefs { get; set; }
        public string Id { get; set; }
        public double Score { get; set; }
    }

    public partial class BestPracticesAuditRef
    {
        public string Id { get; set; }
        public long Weight { get; set; }
    }

    public partial class Performance
    {
        public string Title { get; set; }
        public AccessibilityAuditRef[] AuditRefs { get; set; }
        public string Id { get; set; }
        public double Score { get; set; }
    }

    public partial class CategoryGroups
    {
        public Metrics Metrics { get; set; }
        public A11YAria LoadOpportunities { get; set; }
        public A11YAria Budgets { get; set; }
        public A11YAria Diagnostics { get; set; }
        public Metrics PwaFastReliable { get; set; }
        public Metrics PwaInstallable { get; set; }
        public Metrics PwaOptimized { get; set; }
        public A11YAria A11YBestPractices { get; set; }
        public A11YAria A11YColorContrast { get; set; }
        public A11YAria A11YNamesLabels { get; set; }
        public A11YAria A11YNavigation { get; set; }
        public A11YAria A11YAria { get; set; }
        public A11YAria A11YLanguage { get; set; }
        public A11YAria A11YAudioVideo { get; set; }
        public A11YAria A11YTablesLists { get; set; }
        public A11YAria SeoMobile { get; set; }
        public A11YAria SeoContent { get; set; }
        public A11YAria SeoCrawl { get; set; }
    }

    public partial class A11YAria
    {
        public string Title { get; set; }
        public string Description { get; set; }
    }

    public partial class Metrics
    {
        public string Title { get; set; }
    }

    public partial class ConfigSettings
    {
        public string[] Output { get; set; }
        public long MaxWaitForFcp { get; set; }
        public long MaxWaitForLoad { get; set; }
        public string ThrottlingMethod { get; set; }
        public Throttling Throttling { get; set; }
        public bool AuditMode { get; set; }
        public bool GatherMode { get; set; }
        public bool DisableStorageReset { get; set; }
        public string EmulatedFormFactor { get; set; }
        public string Channel { get; set; }
        public object Budgets { get; set; }
        public string Locale { get; set; }
        public object BlockedUrlPatterns { get; set; }
        public object AdditionalTraceCategories { get; set; }
        public object ExtraHeaders { get; set; }
        public object PrecomputedLanternData { get; set; }
        public object OnlyAudits { get; set; }
        public object OnlyCategories { get; set; }
        public object SkipAudits { get; set; }
    }

    public partial class Throttling
    {
        public long RttMs { get; set; }
        public double ThroughputKbps { get; set; }
        public double RequestLatencyMs { get; set; }
        public double DownloadThroughputKbps { get; set; }
        public long UploadThroughputKbps { get; set; }
        public long CpuSlowdownMultiplier { get; set; }
    }

    public partial class Environment
    {
        public string NetworkUserAgent { get; set; }
        public string HostUserAgent { get; set; }
        public long BenchmarkIndex { get; set; }
    }

    public partial class I18N
    {
        public RendererFormattedStrings RendererFormattedStrings { get; set; }
        public IcuMessagePaths IcuMessagePaths { get; set; }
    }

    public partial class IcuMessagePaths
    {
        public string[] LighthouseCoreAuditsIsOnHttpsJsTitle { get; set; }
        public string[] LighthouseCoreAuditsIsOnHttpsJsDescription { get; set; }
        public string[] LighthouseCoreAuditsRedirectsHttpJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsRedirectsHttpJsDescription { get; set; }
        public string[] LighthouseCoreAuditsServiceWorkerJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsServiceWorkerJsDescription { get; set; }
        public string[] LighthouseCoreAuditsWorksOfflineJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsWorksOfflineJsDescription { get; set; }
        public string[] LighthouseCoreAuditsViewportJsTitle { get; set; }
        public string[] LighthouseCoreAuditsViewportJsDescription { get; set; }
        public string[] LighthouseCoreAuditsWithoutJavascriptJsTitle { get; set; }
        public string[] LighthouseCoreAuditsWithoutJavascriptJsDescription { get; set; }
        public string[] LighthouseCoreAuditsMetricsFirstContentfulPaintJsTitle { get; set; }
        public string[] LighthouseCoreAuditsMetricsFirstContentfulPaintJsDescription { get; set; }
        public LighthouseCore[] LighthouseCoreLibI18NI18NJsSeconds { get; set; }
        public string[] LighthouseCoreAuditsMetricsFirstMeaningfulPaintJsTitle { get; set; }
        public string[] LighthouseCoreAuditsMetricsFirstMeaningfulPaintJsDescription { get; set; }
        public string[] LighthouseCoreAuditsLoadFastEnoughForPwaJsTitle { get; set; }
        public string[] LighthouseCoreAuditsLoadFastEnoughForPwaJsDescription { get; set; }
        public string[] LighthouseCoreAuditsMetricsSpeedIndexJsTitle { get; set; }
        public string[] LighthouseCoreAuditsMetricsSpeedIndexJsDescription { get; set; }
        public string[] LighthouseCoreAuditsMetricsEstimatedInputLatencyJsTitle { get; set; }
        public string[] LighthouseCoreAuditsMetricsEstimatedInputLatencyJsDescription { get; set; }
        public LighthouseCore[] LighthouseCoreLibI18NI18NJsMs { get; set; }
        public string[] LighthouseCoreAuditsMetricsTotalBlockingTimeJsTitle { get; set; }
        public string[] LighthouseCoreAuditsMetricsTotalBlockingTimeJsDescription { get; set; }
        public string[] LighthouseCoreAuditsMetricsMaxPotentialFidJsTitle { get; set; }
        public string[] LighthouseCoreAuditsMetricsMaxPotentialFidJsDescription { get; set; }
        public string[] LighthouseCoreAuditsErrorsInConsoleJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsErrorsInConsoleJsDescription { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsColumnUrl { get; set; }
        public string[] LighthouseCoreAuditsErrorsInConsoleJsColumnDesc { get; set; }
        public string[] LighthouseCoreAuditsTimeToFirstByteJsTitle { get; set; }
        public string[] LighthouseCoreAuditsTimeToFirstByteJsDescription { get; set; }
        public LighthouseCore[] LighthouseCoreAuditsTimeToFirstByteJsDisplayValue { get; set; }
        public string[] LighthouseCoreAuditsMetricsFirstCpuIdleJsTitle { get; set; }
        public string[] LighthouseCoreAuditsMetricsFirstCpuIdleJsDescription { get; set; }
        public string[] LighthouseCoreAuditsMetricsInteractiveJsTitle { get; set; }
        public string[] LighthouseCoreAuditsMetricsInteractiveJsDescription { get; set; }
        public string[] LighthouseCoreAuditsUserTimingsJsTitle { get; set; }
        public string[] LighthouseCoreAuditsUserTimingsJsDescription { get; set; }
        public string[] LighthouseCoreAuditsCriticalRequestChainsJsTitle { get; set; }
        public string[] LighthouseCoreAuditsCriticalRequestChainsJsDescription { get; set; }
        public LighthouseCoreAuditsJsDisplayValue[] LighthouseCoreAuditsCriticalRequestChainsJsDisplayValue { get; set; }
        public string[] LighthouseCoreAuditsRedirectsJsTitle { get; set; }
        public string[] LighthouseCoreAuditsRedirectsJsDescription { get; set; }
        public string[] LighthouseCoreAuditsInstallableManifestJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsInstallableManifestJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAppleTouchIconJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsAppleTouchIconJsDescription { get; set; }
        public string[] LighthouseCoreAuditsSplashScreenJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsSplashScreenJsDescription { get; set; }
        public string[] LighthouseCoreAuditsThemedOmniboxJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsThemedOmniboxJsDescription { get; set; }
        public string[] LighthouseCoreAuditsContentWidthJsTitle { get; set; }
        public string[] LighthouseCoreAuditsContentWidthJsDescription { get; set; }
        public string[] LighthouseCoreAuditsImageAspectRatioJsTitle { get; set; }
        public string[] LighthouseCoreAuditsImageAspectRatioJsDescription { get; set; }
        public string[] LighthouseCoreAuditsDeprecationsJsTitle { get; set; }
        public string[] LighthouseCoreAuditsDeprecationsJsDescription { get; set; }
        public string[] LighthouseCoreAuditsMainthreadWorkBreakdownJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsMainthreadWorkBreakdownJsDescription { get; set; }
        public string[] LighthouseCoreAuditsMainthreadWorkBreakdownJsColumnCategory { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsColumnTimeSpent { get; set; }
        public string[] LighthouseCoreAuditsBootupTimeJsTitle { get; set; }
        public string[] LighthouseCoreAuditsBootupTimeJsDescription { get; set; }
        public string[] LighthouseCoreAuditsBootupTimeJsColumnTotal { get; set; }
        public string[] LighthouseCoreAuditsBootupTimeJsColumnScriptEval { get; set; }
        public string[] LighthouseCoreAuditsBootupTimeJsColumnScriptParse { get; set; }
        public string[] LighthouseCoreAuditsUsesRelPreloadJsTitle { get; set; }
        public string[] LighthouseCoreAuditsUsesRelPreloadJsDescription { get; set; }
        public string[] LighthouseCoreAuditsUsesRelPreconnectJsTitle { get; set; }
        public string[] LighthouseCoreAuditsUsesRelPreconnectJsDescription { get; set; }
        public string[] LighthouseCoreAuditsFontDisplayJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsFontDisplayJsDescription { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsColumnWastedBytes { get; set; }
        public string[] LighthouseCoreAuditsNetworkRttJsTitle { get; set; }
        public string[] LighthouseCoreAuditsNetworkRttJsDescription { get; set; }
        public string[] LighthouseCoreAuditsNetworkServerLatencyJsTitle { get; set; }
        public string[] LighthouseCoreAuditsNetworkServerLatencyJsDescription { get; set; }
        public string[] LighthouseCoreAuditsOfflineStartUrlJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsOfflineStartUrlJsDescription { get; set; }
        public string[] LighthouseCoreAuditsPerformanceBudgetJsTitle { get; set; }
        public string[] LighthouseCoreAuditsPerformanceBudgetJsDescription { get; set; }
        public string[] LighthouseCoreAuditsResourceSummaryJsTitle { get; set; }
        public string[] LighthouseCoreAuditsResourceSummaryJsDescription { get; set; }
        public LighthouseCoreAuditsResourceSummaryJsDisplayValue[] LighthouseCoreAuditsResourceSummaryJsDisplayValue { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsColumnResourceType { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsColumnRequests { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsColumnTransferSize { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsTotalResourceType { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsImageResourceType { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsScriptResourceType { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsStylesheetResourceType { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsFontResourceType { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsDocumentResourceType { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsOtherResourceType { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsMediaResourceType { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsThirdPartyResourceType { get; set; }
        public string[] LighthouseCoreAuditsThirdPartySummaryJsTitle { get; set; }
        public string[] LighthouseCoreAuditsThirdPartySummaryJsDescription { get; set; }
        public string[] LighthouseCoreAuditsManualPwaCrossBrowserJsTitle { get; set; }
        public string[] LighthouseCoreAuditsManualPwaCrossBrowserJsDescription { get; set; }
        public string[] LighthouseCoreAuditsManualPwaPageTransitionsJsTitle { get; set; }
        public string[] LighthouseCoreAuditsManualPwaPageTransitionsJsDescription { get; set; }
        public string[] LighthouseCoreAuditsManualPwaEachPageHasUrlJsTitle { get; set; }
        public string[] LighthouseCoreAuditsManualPwaEachPageHasUrlJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAccesskeysJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAccesskeysJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaAllowedAttrJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaAllowedAttrJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaRequiredAttrJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaRequiredAttrJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaRequiredChildrenJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaRequiredChildrenJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaRequiredParentJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaRequiredParentJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaRolesJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaRolesJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaValidAttrValueJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaValidAttrValueJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaValidAttrJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAriaValidAttrJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAudioCaptionJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAudioCaptionJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityButtonNameJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityButtonNameJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityBypassJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityBypassJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityColorContrastJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityColorContrastJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityAxeAuditJsFailingElementsHeader { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityDefinitionListJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityDefinitionListJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityDlitemJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityDlitemJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityDocumentTitleJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityDocumentTitleJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityDuplicateIdJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityDuplicateIdJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityFrameTitleJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityFrameTitleJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityHtmlHasLangJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityHtmlHasLangJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityHtmlLangValidJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityHtmlLangValidJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityImageAltJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityImageAltJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityInputImageAltJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityInputImageAltJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityLabelJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityLabelJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityLayoutTableJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityLayoutTableJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityLinkNameJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityLinkNameJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityListJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityListJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityListitemJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityListitemJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityMetaRefreshJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityMetaRefreshJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityMetaViewportJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityMetaViewportJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityObjectAltJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityObjectAltJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityTabindexJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityTabindexJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityTdHeadersAttrJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityTdHeadersAttrJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityThHasDataCellsJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityThHasDataCellsJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityValidLangJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityValidLangJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityVideoCaptionJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityVideoCaptionJsDescription { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityVideoDescriptionJsTitle { get; set; }
        public string[] LighthouseCoreAuditsAccessibilityVideoDescriptionJsDescription { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUsesLongCacheTtlJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUsesLongCacheTtlJsDescription { get; set; }
        public LighthouseCoreAuditsJsDisplayValue[] LighthouseCoreAuditsByteEfficiencyUsesLongCacheTtlJsDisplayValue { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsColumnCacheTtl { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsColumnSize { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyTotalByteWeightJsTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyTotalByteWeightJsDescription { get; set; }
        public LighthouseCoreAuditsByteEfficiencyTotalByteWeightJsDisplayValue[] LighthouseCoreAuditsByteEfficiencyTotalByteWeightJsDisplayValue { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyOffscreenImagesJsTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyOffscreenImagesJsDescription { get; set; }
        public LighthouseCoreLibI18NI18NJsDisplayValueByteSaving[] LighthouseCoreLibI18NI18NJsDisplayValueByteSavings { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyRenderBlockingResourcesJsTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyRenderBlockingResourcesJsDescription { get; set; }
        public LighthouseCoreLibI18NI18NJsDisplayValueMsSaving[] LighthouseCoreLibI18NI18NJsDisplayValueMsSavings { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUnminifiedCssJsTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUnminifiedCssJsDescription { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUnminifiedJavascriptJsTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUnminifiedJavascriptJsDescription { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUnusedCssRulesJsTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUnusedCssRulesJsDescription { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUsesWebpImagesJsTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUsesWebpImagesJsDescription { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUsesOptimizedImagesJsTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUsesOptimizedImagesJsDescription { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUsesTextCompressionJsTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUsesTextCompressionJsDescription { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUsesResponsiveImagesJsTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyUsesResponsiveImagesJsDescription { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyEfficientAnimatedContentJsTitle { get; set; }
        public string[] LighthouseCoreAuditsByteEfficiencyEfficientAnimatedContentJsDescription { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebAppcacheManifestJsTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebAppcacheManifestJsDescription { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebDoctypeJsTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebDoctypeJsDescription { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebDomSizeJsTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebDomSizeJsDescription { get; set; }
        public LighthouseCoreAuditsJsDisplayValue[] LighthouseCoreAuditsDobetterwebDomSizeJsDisplayValue { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebDomSizeJsColumnStatistic { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebDomSizeJsColumnElement { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebDomSizeJsColumnValue { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebDomSizeJsStatisticDomElements { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebDomSizeJsStatisticDomDepth { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebDomSizeJsStatisticDomWidth { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebExternalAnchorsUseRelNoopenerJsTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebExternalAnchorsUseRelNoopenerJsDescription { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebGeolocationOnStartJsTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebGeolocationOnStartJsDescription { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebNoDocumentWriteJsTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebNoDocumentWriteJsDescription { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebNoVulnerableLibrariesJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebNoVulnerableLibrariesJsDescription { get; set; }
        public LighthouseCoreAuditsJsDisplayValue[] LighthouseCoreAuditsDobetterwebNoVulnerableLibrariesJsDisplayValue { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebNoVulnerableLibrariesJsColumnVersion { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebNoVulnerableLibrariesJsColumnVuln { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebNoVulnerableLibrariesJsColumnSeverity { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebNoVulnerableLibrariesJsRowSeverityMedium { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebNoVulnerableLibrariesJsRowSeverityHigh { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebJsLibrariesJsTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebJsLibrariesJsDescription { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsColumnName { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebJsLibrariesJsColumnVersion { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebNotificationOnStartJsTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebNotificationOnStartJsDescription { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebPasswordInputsCanBePastedIntoJsTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebPasswordInputsCanBePastedIntoJsDescription { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebUsesHttp2JsTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebUsesHttp2JsDescription { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebUsesPassiveEventListenersJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsDobetterwebUsesPassiveEventListenersJsDescription { get; set; }
        public string[] LighthouseCoreLibI18NI18NJsColumnLocation { get; set; }
        public string[] LighthouseCoreAuditsSeoMetaDescriptionJsTitle { get; set; }
        public string[] LighthouseCoreAuditsSeoMetaDescriptionJsDescription { get; set; }
        public string[] LighthouseCoreAuditsSeoHttpStatusCodeJsTitle { get; set; }
        public string[] LighthouseCoreAuditsSeoHttpStatusCodeJsDescription { get; set; }
        public string[] LighthouseCoreAuditsSeoFontSizeJsTitle { get; set; }
        public string[] LighthouseCoreAuditsSeoFontSizeJsDescription { get; set; }
        public LighthouseCoreAuditsSeoJsDisplayValue[] LighthouseCoreAuditsSeoFontSizeJsDisplayValue { get; set; }
        public string[] LighthouseCoreAuditsSeoLinkTextJsTitle { get; set; }
        public string[] LighthouseCoreAuditsSeoLinkTextJsDescription { get; set; }
        public string[] LighthouseCoreAuditsSeoIsCrawlableJsFailureTitle { get; set; }
        public string[] LighthouseCoreAuditsSeoIsCrawlableJsDescription { get; set; }
        public string[] LighthouseCoreAuditsSeoRobotsTxtJsTitle { get; set; }
        public string[] LighthouseCoreAuditsSeoRobotsTxtJsDescription { get; set; }
        public string[] LighthouseCoreAuditsSeoTapTargetsJsTitle { get; set; }
        public string[] LighthouseCoreAuditsSeoTapTargetsJsDescription { get; set; }
        public LighthouseCoreAuditsSeoJsDisplayValue[] LighthouseCoreAuditsSeoTapTargetsJsDisplayValue { get; set; }
        public string[] LighthouseCoreAuditsSeoHreflangJsTitle { get; set; }
        public string[] LighthouseCoreAuditsSeoHreflangJsDescription { get; set; }
        public string[] LighthouseCoreAuditsSeoPluginsJsTitle { get; set; }
        public string[] LighthouseCoreAuditsSeoPluginsJsDescription { get; set; }
        public string[] LighthouseCoreAuditsSeoCanonicalJsTitle { get; set; }
        public string[] LighthouseCoreAuditsSeoCanonicalJsDescription { get; set; }
        public string[] LighthouseCoreAuditsSeoManualStructuredDataJsTitle { get; set; }
        public string[] LighthouseCoreAuditsSeoManualStructuredDataJsDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsPerformanceCategoryTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YCategoryTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YCategoryDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YCategoryManualDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsBestPracticesCategoryTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsSeoCategoryTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsSeoCategoryDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsSeoCategoryManualDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsPwaCategoryTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsPwaCategoryDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsPwaCategoryManualDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsMetricGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsLoadOpportunitiesGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsLoadOpportunitiesGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsBudgetsGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsBudgetsGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsDiagnosticsGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsDiagnosticsGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsPwaFastReliableGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsPwaInstallableGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsPwaOptimizedGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YBestPracticesGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YBestPracticesGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YColorContrastGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YColorContrastGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YNamesLabelsGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YNamesLabelsGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YNavigationGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YNavigationGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YAriaGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YAriaGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YLanguageGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YLanguageGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YAudioVideoGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YAudioVideoGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YTablesListsVideoGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsA11YTablesListsVideoGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsSeoMobileGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsSeoMobileGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsSeoContentGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsSeoContentGroupDescription { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsSeoCrawlingGroupTitle { get; set; }
        public string[] LighthouseCoreConfigDefaultConfigJsSeoCrawlingGroupDescription { get; set; }
    }

    public partial class LighthouseCoreAuditsByteEfficiencyTotalByteWeightJsDisplayValue
    {
        public LighthouseCoreAuditsByteEfficiencyTotalByteWeightJsDisplayValueValues Values { get; set; }
        public string Path { get; set; }
    }

    public partial class LighthouseCoreAuditsByteEfficiencyTotalByteWeightJsDisplayValueValues
    {
        public long TotalBytes { get; set; }
    }

    public partial class LighthouseCoreAuditsJsDisplayValue
    {
        public LighthouseCoreAuditsByteEfficiencyUsesLongCacheTtlJsDisplayValueValues Values { get; set; }
        public string Path { get; set; }
    }

    public partial class LighthouseCoreAuditsByteEfficiencyUsesLongCacheTtlJsDisplayValueValues
    {
        public long ItemCount { get; set; }
    }

    public partial class LighthouseCoreAuditsResourceSummaryJsDisplayValue
    {
        public LighthouseCoreAuditsResourceSummaryJsDisplayValueValues Values { get; set; }
        public string Path { get; set; }
    }

    public partial class LighthouseCoreAuditsResourceSummaryJsDisplayValueValues
    {
        public long RequestCount { get; set; }
        public long ByteCount { get; set; }
    }

    public partial class LighthouseCoreAuditsSeoJsDisplayValue
    {
        public LighthouseCoreAuditsSeoFontSizeJsDisplayValueValues Values { get; set; }
        public string Path { get; set; }
    }

    public partial class LighthouseCoreAuditsSeoFontSizeJsDisplayValueValues
    {
        public double DecimalProportion { get; set; }
    }

    public partial class LighthouseCore
    {
        public LighthouseCoreAuditsTimeToFirstByteJsDisplayValueValues Values { get; set; }
        public string Path { get; set; }
    }

    public partial class LighthouseCoreAuditsTimeToFirstByteJsDisplayValueValues
    {
        public double TimeInMs { get; set; }
    }

    public partial class LighthouseCoreLibI18NI18NJsDisplayValueByteSaving
    {
        public ValuesClass Values { get; set; }
        public string Path { get; set; }
    }

    public partial class LighthouseCoreLibI18NI18NJsDisplayValueMsSaving
    {
        public LighthouseCoreLibI18NI18NJsDisplayValueMsSavingValues Values { get; set; }
        public string Path { get; set; }
    }

    public partial class LighthouseCoreLibI18NI18NJsDisplayValueMsSavingValues
    {
        public double WastedMs { get; set; }
    }

    public partial class RendererFormattedStrings
    {
        public string AuditGroupExpandTooltip { get; set; }
        public string CrcInitialNavigation { get; set; }
        public string CrcLongestDurationLabel { get; set; }
        public string ErrorLabel { get; set; }
        public string ErrorMissingAuditInfo { get; set; }
        public string LabDataTitle { get; set; }
        public string LsPerformanceCategoryDescription { get; set; }
        public string ManualAuditsGroupTitle { get; set; }
        public string NotApplicableAuditsGroupTitle { get; set; }
        public string OpportunityResourceColumnLabel { get; set; }
        public string OpportunitySavingsColumnLabel { get; set; }
        public string PassedAuditsGroupTitle { get; set; }
        public string SnippetCollapseButtonLabel { get; set; }
        public string SnippetExpandButtonLabel { get; set; }
        public string ThirdPartyResourcesLabel { get; set; }
        public string ToplevelWarningsMessage { get; set; }
        public string VarianceDisclaimer { get; set; }
        public string WarningAuditsGroupTitle { get; set; }
        public string WarningHeader { get; set; }
    }

    public partial class Timing
    {
        public Entry[] Entries { get; set; }
        public double Total { get; set; }
    }

    public partial class Entry
    {
        public double StartTime { get; set; }
        public string Name { get; set; }
        public double Duration { get; set; }
        public EntryType EntryType { get; set; }
    }

    public enum DebugDataType { Criticalrequestchain, Debugdata, Filmstrip, Opportunity, Screenshot, Table };

    public enum ValueType { Bytes, Thumbnail, TimespanMs, Url };

    public enum NodeType { Node };

    public enum SourceEnum { LegibleText, Network, RuntimeException };

    public enum ScoreDisplayMode { Binary, Informative, Manual, NotApplicable, Numeric };

    public enum MimeType { ApplicationJavascript, ApplicationOctetStream, ApplicationXJavascript, ImageJpeg, ImageSvgXml, TextCss, TextHtml };

    public enum EntryType { Measure };

    public partial struct ElementUnion
    {
        public ElementClass ElementClass;
        public string String;

        public static implicit operator ElementUnion(ElementClass ElementClass) => new ElementUnion { ElementClass = ElementClass };
        public static implicit operator ElementUnion(string String) => new ElementUnion { String = String };
    }

    public partial struct SourceUnion
    {
        public ElementClass ElementClass;
        public SourceEnum? Enum;
        public Uri PurpleUri;

        public static implicit operator SourceUnion(ElementClass ElementClass) => new SourceUnion { ElementClass = ElementClass };
        public static implicit operator SourceUnion(SourceEnum Enum) => new SourceUnion { Enum = Enum };
        public static implicit operator SourceUnion(Uri PurpleUri) => new SourceUnion { PurpleUri = PurpleUri };
    }
}
