//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Lighthouse.Model.Autogenerated.Foundation.Lighthouse.Concrete
{


    /// <summary>Represents the /sitecore/templates/Foundation/Lighthouse/Concrete/LighthouseSite template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{E0ED4F14-6C04-41F4-B09B-76D733F63D67}", "xGyJ0gxyGPnBgnzIjj1Vx57wkGE=", "Default Configuration")]
    public partial interface ILighthouseSiteItem : global::Foundation.Lighthouse.Model.Autogenerated.Foundation.Lighthouse.Partial.I_LighthouseItem, global::Foundation.Lighthouse.Model.Autogenerated.Foundation.Lighthouse.Partial.I_LighthouseSiteItem
    {
    }
}
namespace Foundation.Lighthouse.Model.Autogenerated.Foundation.Lighthouse.Partial
{


    /// <summary>Represents the /sitecore/templates/Foundation/Lighthouse/Partial/_Lighthouse template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{BB102C6B-C167-4453-9A76-BC44F8889424}", "tnlCTTkIkSf0zOOkecDTTKCI5+Y=", "Default Configuration")]
    public partial interface I_LighthouseItem : Synthesis.IStandardTemplateItem
    {

        /// <summary>Represents the Data field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("data")]
        Synthesis.FieldTypes.Interfaces.ITextField Data
        {
            get;
        }

        /// <summary>Represents the Perfomance field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("perfomance")]
        Synthesis.FieldTypes.Interfaces.ITextField Perfomance
        {
            get;
        }

        /// <summary>Represents the Accessibility field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("accessibility")]
        Synthesis.FieldTypes.Interfaces.ITextField Accessibility
        {
            get;
        }

        /// <summary>Represents the BestPractices field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("bestpractices")]
        Synthesis.FieldTypes.Interfaces.ITextField BestPractices
        {
            get;
        }

        /// <summary>Represents the SEO field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("seo")]
        Synthesis.FieldTypes.Interfaces.ITextField SEO
        {
            get;
        }
    }

    /// <summary>Represents the /sitecore/templates/Foundation/Lighthouse/Partial/_LighthouseSite template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{A5A2DC56-30EE-45A6-8E94-FE57007420C3}", "ExQ12phF3f+SZgRpY7q5l6pg3ho=", "Default Configuration")]
    public partial interface I_LighthouseSiteItem : Synthesis.IStandardTemplateItem
    {

        /// <summary>Represents the Sitename field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("sitename")]
        Synthesis.FieldTypes.Interfaces.ITextField Sitename
        {
            get;
        }

        /// <summary>Represents the Worst Items field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("worst_items")]
        Synthesis.FieldTypes.Interfaces.ITextField WorstItems
        {
            get;
        }

        /// <summary>Represents the Best Items field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("best_items")]
        Synthesis.FieldTypes.Interfaces.ITextField BestItems
        {
            get;
        }

        /// <summary>Represents the Logs field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("logs")]
        Synthesis.FieldTypes.Interfaces.ITextField Logs
        {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Lighthouse.Model.Autogenerated.Concrete.Foundation.Lighthouse.Concrete
{


    /// <summary>Represents the /sitecore/templates/Foundation/Lighthouse/Concrete/LighthouseSite template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public partial class LighthouseSite : global::Synthesis.StandardTemplateItem, global::Foundation.Lighthouse.Model.Autogenerated.Foundation.Lighthouse.Concrete.ILighthouseSiteItem
    {

        private Synthesis.FieldTypes.TextField _data;

        private Synthesis.FieldTypes.TextField _sitename;

        private Synthesis.FieldTypes.TextField _perfomance;

        private Synthesis.FieldTypes.TextField _worstItems;

        private Synthesis.FieldTypes.TextField _accessibility;

        private Synthesis.FieldTypes.TextField _bestItems;

        private Synthesis.FieldTypes.TextField _bestPractices;

        private Synthesis.FieldTypes.TextField _logs;

        private Synthesis.FieldTypes.TextField _sEO;

        public LighthouseSite(Sitecore.Data.Items.Item innerItem) :
                base(innerItem)
        {
        }

        public LighthouseSite(global::System.Collections.Generic.IDictionary<string, string> searchFields) :
                base(searchFields)
        {
        }

        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName
        {
            get
            {
                return "LighthouseSite";
            }
        }

        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId
        {
            get
            {
                return new Sitecore.Data.ID("{E0ED4F14-6C04-41F4-B09B-76D733F63D67}");
            }
        }

        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId
        {
            get
            {
                return ItemTemplateId;
            }
        }

        /// <summary>Represents the Data field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("data")]
        public Synthesis.FieldTypes.Interfaces.ITextField Data
        {
            get
            {
                if (_data == null)
                {
                    _data = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2B81B040-5376-4C5C-81F2-EBB106D4BD29}"], "/sitecore/templates/Foundation/Lighthouse/Concrete/LighthouseSite", "Data"), this.GetSearchFieldValue("data"));
                }
                return _data;
            }
        }

        /// <summary>Represents the Sitename field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("sitename")]
        public Synthesis.FieldTypes.Interfaces.ITextField Sitename
        {
            get
            {
                if (_sitename == null)
                {
                    _sitename = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{160BD99B-D3C1-4A00-98E5-07F6E060B2DD}"], "/sitecore/templates/Foundation/Lighthouse/Concrete/LighthouseSite", "Sitename"), this.GetSearchFieldValue("sitename"));
                }
                return _sitename;
            }
        }

        /// <summary>Represents the Perfomance field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("perfomance")]
        public Synthesis.FieldTypes.Interfaces.ITextField Perfomance
        {
            get
            {
                if (_perfomance == null)
                {
                    _perfomance = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3D927627-E1B5-4D61-B946-C83BE74C78A3}"], "/sitecore/templates/Foundation/Lighthouse/Concrete/LighthouseSite", "Perfomance"), this.GetSearchFieldValue("perfomance"));
                }
                return _perfomance;
            }
        }

        /// <summary>Represents the Worst Items field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("worst_items")]
        public Synthesis.FieldTypes.Interfaces.ITextField WorstItems
        {
            get
            {
                if (_worstItems == null)
                {
                    _worstItems = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{A675A66B-98FA-4D00-8700-FEB32644B60F}"], "/sitecore/templates/Foundation/Lighthouse/Concrete/LighthouseSite", "Worst Items"), this.GetSearchFieldValue("worst_items"));
                }
                return _worstItems;
            }
        }

        /// <summary>Represents the Accessibility field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("accessibility")]
        public Synthesis.FieldTypes.Interfaces.ITextField Accessibility
        {
            get
            {
                if (_accessibility == null)
                {
                    _accessibility = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{69C93298-AB4A-4F64-99BA-C08A3397B7B5}"], "/sitecore/templates/Foundation/Lighthouse/Concrete/LighthouseSite", "Accessibility"), this.GetSearchFieldValue("accessibility"));
                }
                return _accessibility;
            }
        }

        /// <summary>Represents the Best Items field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("best_items")]
        public Synthesis.FieldTypes.Interfaces.ITextField BestItems
        {
            get
            {
                if (_bestItems == null)
                {
                    _bestItems = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{65DCE205-4163-4D01-B3DB-2DCF5C4513BD}"], "/sitecore/templates/Foundation/Lighthouse/Concrete/LighthouseSite", "Best Items"), this.GetSearchFieldValue("best_items"));
                }
                return _bestItems;
            }
        }

        /// <summary>Represents the BestPractices field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("bestpractices")]
        public Synthesis.FieldTypes.Interfaces.ITextField BestPractices
        {
            get
            {
                if (_bestPractices == null)
                {
                    _bestPractices = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{A81C12DC-3C3F-471E-8F9F-1A481FCDAA17}"], "/sitecore/templates/Foundation/Lighthouse/Concrete/LighthouseSite", "BestPractices"), this.GetSearchFieldValue("bestpractices"));
                }
                return _bestPractices;
            }
        }

        /// <summary>Represents the Logs field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("logs")]
        public Synthesis.FieldTypes.Interfaces.ITextField Logs
        {
            get
            {
                if (_logs == null)
                {
                    _logs = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{0723548C-2C72-4387-8D83-893230DB601C}"], "/sitecore/templates/Foundation/Lighthouse/Concrete/LighthouseSite", "Logs"), this.GetSearchFieldValue("logs"));
                }
                return _logs;
            }
        }

        /// <summary>Represents the SEO field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("seo")]
        public Synthesis.FieldTypes.Interfaces.ITextField SEO
        {
            get
            {
                if (_sEO == null)
                {
                    _sEO = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2CBB7894-D510-4CE3-A1ED-FD9DC93A76E1}"], "/sitecore/templates/Foundation/Lighthouse/Concrete/LighthouseSite", "SEO"), this.GetSearchFieldValue("seo"));
                }
                return _sEO;
            }
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public class LighthouseSiteInitializer : Synthesis.Initializers.ITemplateInitializer
    {

        public Sitecore.Data.ID InitializesTemplateId
        {
            get
            {
                return new Sitecore.Data.ID("{E0ED4F14-6C04-41F4-B09B-76D733F63D67}");
            }
        }

        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem)
        {
            return new LighthouseSite(innerItem);
        }

        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields)
        {
            return new LighthouseSite(searchFields);
        }
    }
}
namespace Foundation.Lighthouse.Model.Autogenerated.Concrete.Foundation.Lighthouse.Partial
{


    /// <summary>Represents the /sitecore/templates/Foundation/Lighthouse/Partial/_Lighthouse template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public partial class _Lighthouse : global::Synthesis.StandardTemplateItem, global::Foundation.Lighthouse.Model.Autogenerated.Foundation.Lighthouse.Partial.I_LighthouseItem
    {

        private Synthesis.FieldTypes.TextField _data;

        private Synthesis.FieldTypes.TextField _perfomance;

        private Synthesis.FieldTypes.TextField _accessibility;

        private Synthesis.FieldTypes.TextField _bestPractices;

        private Synthesis.FieldTypes.TextField _sEO;

        public _Lighthouse(Sitecore.Data.Items.Item innerItem) :
                base(innerItem)
        {
        }

        public _Lighthouse(global::System.Collections.Generic.IDictionary<string, string> searchFields) :
                base(searchFields)
        {
        }

        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName
        {
            get
            {
                return "_Lighthouse";
            }
        }

        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId
        {
            get
            {
                return new Sitecore.Data.ID("{BB102C6B-C167-4453-9A76-BC44F8889424}");
            }
        }

        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId
        {
            get
            {
                return ItemTemplateId;
            }
        }

        /// <summary>Represents the Data field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("data")]
        public Synthesis.FieldTypes.Interfaces.ITextField Data
        {
            get
            {
                if (_data == null)
                {
                    _data = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2B81B040-5376-4C5C-81F2-EBB106D4BD29}"], "/sitecore/templates/Foundation/Lighthouse/Partial/_Lighthouse", "Data"), this.GetSearchFieldValue("data"));
                }
                return _data;
            }
        }

        /// <summary>Represents the Perfomance field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("perfomance")]
        public Synthesis.FieldTypes.Interfaces.ITextField Perfomance
        {
            get
            {
                if (_perfomance == null)
                {
                    _perfomance = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3D927627-E1B5-4D61-B946-C83BE74C78A3}"], "/sitecore/templates/Foundation/Lighthouse/Partial/_Lighthouse", "Perfomance"), this.GetSearchFieldValue("perfomance"));
                }
                return _perfomance;
            }
        }

        /// <summary>Represents the Accessibility field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("accessibility")]
        public Synthesis.FieldTypes.Interfaces.ITextField Accessibility
        {
            get
            {
                if (_accessibility == null)
                {
                    _accessibility = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{69C93298-AB4A-4F64-99BA-C08A3397B7B5}"], "/sitecore/templates/Foundation/Lighthouse/Partial/_Lighthouse", "Accessibility"), this.GetSearchFieldValue("accessibility"));
                }
                return _accessibility;
            }
        }

        /// <summary>Represents the BestPractices field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("bestpractices")]
        public Synthesis.FieldTypes.Interfaces.ITextField BestPractices
        {
            get
            {
                if (_bestPractices == null)
                {
                    _bestPractices = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{A81C12DC-3C3F-471E-8F9F-1A481FCDAA17}"], "/sitecore/templates/Foundation/Lighthouse/Partial/_Lighthouse", "BestPractices"), this.GetSearchFieldValue("bestpractices"));
                }
                return _bestPractices;
            }
        }

        /// <summary>Represents the SEO field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("seo")]
        public Synthesis.FieldTypes.Interfaces.ITextField SEO
        {
            get
            {
                if (_sEO == null)
                {
                    _sEO = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2CBB7894-D510-4CE3-A1ED-FD9DC93A76E1}"], "/sitecore/templates/Foundation/Lighthouse/Partial/_Lighthouse", "SEO"), this.GetSearchFieldValue("seo"));
                }
                return _sEO;
            }
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public class _LighthouseInitializer : Synthesis.Initializers.ITemplateInitializer
    {

        public Sitecore.Data.ID InitializesTemplateId
        {
            get
            {
                return new Sitecore.Data.ID("{BB102C6B-C167-4453-9A76-BC44F8889424}");
            }
        }

        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem)
        {
            return new _Lighthouse(innerItem);
        }

        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields)
        {
            return new _Lighthouse(searchFields);
        }
    }

    /// <summary>Represents the /sitecore/templates/Foundation/Lighthouse/Partial/_LighthouseSite template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public partial class _LighthouseSite : global::Synthesis.StandardTemplateItem, global::Foundation.Lighthouse.Model.Autogenerated.Foundation.Lighthouse.Partial.I_LighthouseSiteItem
    {

        private Synthesis.FieldTypes.TextField _sitename;

        private Synthesis.FieldTypes.TextField _worstItems;

        private Synthesis.FieldTypes.TextField _bestItems;

        private Synthesis.FieldTypes.TextField _logs;

        public _LighthouseSite(Sitecore.Data.Items.Item innerItem) :
                base(innerItem)
        {
        }

        public _LighthouseSite(global::System.Collections.Generic.IDictionary<string, string> searchFields) :
                base(searchFields)
        {
        }

        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName
        {
            get
            {
                return "_LighthouseSite";
            }
        }

        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId
        {
            get
            {
                return new Sitecore.Data.ID("{A5A2DC56-30EE-45A6-8E94-FE57007420C3}");
            }
        }

        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId
        {
            get
            {
                return ItemTemplateId;
            }
        }

        /// <summary>Represents the Sitename field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("sitename")]
        public Synthesis.FieldTypes.Interfaces.ITextField Sitename
        {
            get
            {
                if (_sitename == null)
                {
                    _sitename = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{160BD99B-D3C1-4A00-98E5-07F6E060B2DD}"], "/sitecore/templates/Foundation/Lighthouse/Partial/_LighthouseSite", "Sitename"), this.GetSearchFieldValue("sitename"));
                }
                return _sitename;
            }
        }

        /// <summary>Represents the Worst Items field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("worst_items")]
        public Synthesis.FieldTypes.Interfaces.ITextField WorstItems
        {
            get
            {
                if (_worstItems == null)
                {
                    _worstItems = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{A675A66B-98FA-4D00-8700-FEB32644B60F}"], "/sitecore/templates/Foundation/Lighthouse/Partial/_LighthouseSite", "Worst Items"), this.GetSearchFieldValue("worst_items"));
                }
                return _worstItems;
            }
        }

        /// <summary>Represents the Best Items field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("best_items")]
        public Synthesis.FieldTypes.Interfaces.ITextField BestItems
        {
            get
            {
                if (_bestItems == null)
                {
                    _bestItems = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{65DCE205-4163-4D01-B3DB-2DCF5C4513BD}"], "/sitecore/templates/Foundation/Lighthouse/Partial/_LighthouseSite", "Best Items"), this.GetSearchFieldValue("best_items"));
                }
                return _bestItems;
            }
        }

        /// <summary>Represents the Logs field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("logs")]
        public Synthesis.FieldTypes.Interfaces.ITextField Logs
        {
            get
            {
                if (_logs == null)
                {
                    _logs = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{0723548C-2C72-4387-8D83-893230DB601C}"], "/sitecore/templates/Foundation/Lighthouse/Partial/_LighthouseSite", "Logs"), this.GetSearchFieldValue("logs"));
                }
                return _logs;
            }
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "9.1")]
    public class _LighthouseSiteInitializer : Synthesis.Initializers.ITemplateInitializer
    {

        public Sitecore.Data.ID InitializesTemplateId
        {
            get
            {
                return new Sitecore.Data.ID("{A5A2DC56-30EE-45A6-8E94-FE57007420C3}");
            }
        }

        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem)
        {
            return new _LighthouseSite(innerItem);
        }

        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields)
        {
            return new _LighthouseSite(searchFields);
        }
    }
}
