using System;
using System.Collections.Concurrent;
using System.IO;
using Foundation.Lighthouse.Model.Autogenerated;
using Newtonsoft.Json;
using Sitecore.Data.Items;

namespace Foundation.Lighthouse
{
    public class LighthouseRunner : ILighthouseRunner
    {
        private readonly IPaths _paths;
        private readonly IUrls _urls;
        private ISitecoreData _sitecoreData;
        public LighthouseRunner(IPaths paths, IUrls urls, ISitecoreData sitecoreData)
        {
            _paths = paths;
            _urls = urls;
            _sitecoreData = sitecoreData;
        }
        public bool Run(Item item, OutputFormat format)
        {
            var processOutput = new ConcurrentBag<string>();
            _paths.CreateReportDir(item);
            
            var process = new System.Diagnostics.Process();
            var startInfo = new System.Diagnostics.ProcessStartInfo();
            startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
            startInfo.FileName = _paths.GetLighthouseCmdPath();
            //startInfo.Arguments = $"/c \"";
            startInfo.Arguments += $"{_urls.GetItemUrl(item)}";
            var path = "";
            switch (format)
            {
                case OutputFormat.Html:
                    path = _paths.GetReportHtmlPath(item);
                    break;
                case OutputFormat.Json:
                    path = _paths.GetReportJsonPath(item);
                    startInfo.Arguments += GetOutputFormat(format);
                    break;
            }

            startInfo.Arguments += GetOutputPath(path);
            startInfo.Arguments += " --chrome-flags=\"--ignore-certificate-errors\"";

            //startInfo.Arguments += "\"";
            //startInfo.UseShellExecute = false;
            //startInfo.RedirectStandardOutput = true;
            //startInfo.RedirectStandardError = true;
            startInfo.UseShellExecute = false;
            startInfo.RedirectStandardOutput = true;
            startInfo.RedirectStandardError = true;
            process.StartInfo = startInfo;
            process.OutputDataReceived += (sender, eventArgs) => processOutput.Add(eventArgs.Data);
            process.ErrorDataReceived += (sender, eventArgs) => processOutput.Add(eventArgs.Data);

            Sitecore.Diagnostics.Log.Error(startInfo.FileName, this);
            Sitecore.Diagnostics.Log.Error(startInfo.Arguments, this);
            process.Start();
            process.BeginOutputReadLine();
            process.BeginErrorReadLine();
            process.WaitForExit(20000);

            if (format == OutputFormat.Json)
            {
                var json = File.ReadAllText(path);
                var model = JsonConvert.DeserializeObject<LighthouseJson>(json);
                _sitecoreData.AddCheckPoint(item, model);
            }
            return process.ExitCode == 0;
        }

        private string GetOutputPath(string path)
        {
            return $" --output-path {path}";
        }

        private string GetOutputFormat(OutputFormat format)
        {
            return $" --output {Enum.GetName(typeof(OutputFormat), format)?.ToLower()}";
        }
    }
}